import { useState } from 'react';
import { ArrowRight, BookOpen, Check, SlidersHorizontal } from 'lucide-react';
import { Badge, BookCover, Button, EmptyState, Modal, SearchInput } from './ui';
import { dateLabel, isOpenLoan, relativeDay, userId } from './data';

export default function Catalogue({ data, user, onBorrow, onViewLoans }) {
  const [search, setSearch] = useState('');
  const [genre, setGenre] = useState('');
  const [publisher, setPublisher] = useState('');
  const [selected, setSelected] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);
  const books = data.books.filter((book) => `${book.judul} ${book.penulis}`.toLowerCase().includes(search.toLowerCase()) && (!genre || String(book.id_genre) === genre) && (!publisher || String(book.id_penerbit) === publisher));
  const hasLoan = (book) => data.loans.some((loan) => String(loan.id_user) === String(userId(user)) && String(loan.id_buku) === String(book.id_buku) && isOpenLoan(loan));
  async function borrow() {
    setBusy(true); setError('');
    try { await onBorrow(selected); setSuccess(true); } catch (error) { setError(error.message); } finally { setBusy(false); }
  }
  return <>
    <section className="mb-7 flex flex-wrap items-center gap-3 rounded-lg border border-stone-200 bg-white p-4"><SearchInput value={search} onChange={setSearch} /><SlidersHorizontal aria-hidden="true" className="hidden size-4 text-stone-400 sm:block" /><select className="dash-input w-auto max-w-full" value={genre} aria-label="Filter genre" onChange={(event) => setGenre(event.target.value)}><option value="">Semua genre</option>{data.genres.map((item) => <option key={item.id_genre} value={item.id_genre}>{item.nama_genre}</option>)}</select><select className="dash-input w-auto max-w-full" value={publisher} aria-label="Filter penerbit" onChange={(event) => setPublisher(event.target.value)}><option value="">Semua penerbit</option>{data.publishers.map((item) => <option key={item.id_penerbit} value={item.id_penerbit}>{item.nama_penerbit}</option>)}</select></section>
    <div className="mb-5 flex items-center justify-between"><h2 className="font-serif text-xl">Temukan bacaan berikutnya.</h2><span className="text-[10px] text-stone-500">{books.length} judul</span></div>
    {!books.length ? <EmptyState title="Belum menemukan bukunya?" description="Coba kata kunci lain atau ubah filter genre dan penerbit." /> : <div className="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-4">{books.map((book) => <article key={book.id_buku} className="group flex flex-col overflow-hidden rounded-lg border border-stone-200 bg-white"><button onClick={() => { setSelected(book); setSuccess(false); setError(''); }} aria-label={`Lihat detail ${book.judul}`} className="flex h-52 items-center justify-center bg-[#f0ede6] p-5 sm:h-60"><BookCover book={book} className="h-full aspect-[2/3] rounded-r shadow-[3px_5px_10px_#29252425] transition-transform duration-300 group-hover:-translate-y-1 motion-reduce:transform-none" /></button><div className="flex flex-1 flex-col p-4"><p className="text-[8px] uppercase tracking-[0.15em] text-stone-400">{data.genres.find((genre) => String(genre.id_genre) === String(book.id_genre))?.nama_genre || 'Koleksi'}</p><h3 className="mt-2 font-serif text-xl leading-6">{book.judul}</h3><p className="mb-4 mt-2 text-[10px] text-stone-500">{book.penulis}</p><div className="mt-auto flex flex-wrap items-center justify-between gap-2 border-t border-stone-100 pt-3"><Badge tone={book.stok > 0 ? 'success' : 'neutral'}>{book.stok > 0 ? `${book.stok} tersedia` : 'Stok habis'}</Badge><button onClick={() => { setSelected(book); setSuccess(false); setError(''); }} className="flex items-center gap-1 text-[10px] font-medium">Detail <ArrowRight className="size-3" /></button></div></div></article>)}</div>}
    {selected && <Modal title={success ? 'Satu cerita baru menanti.' : 'Pinjam buku'} onClose={() => setSelected(null)} busy={busy} description={success ? 'Pengajuan Anda sudah dicatat.' : 'Periksa detail buku sebelum mengajukan peminjaman.'}>
      {success ? <><div className="mb-5 flex size-12 items-center justify-center rounded-full bg-[#eef2e9] text-[#536346]"><Check className="size-6" /></div><p className="text-sm leading-7 text-stone-600">Pengajuan <strong>{selected.judul}</strong> menunggu konfirmasi petugas. Lihat status dan batas pengembalian di Peminjaman Saya.</p>{data.mode === 'demo' && <p className="mt-4 text-xs text-stone-500">Ini simulasi; tidak ada transaksi yang dikirim ke server.</p>}<Button className="mt-6 w-full" onClick={onViewLoans}>Lihat peminjaman saya <ArrowRight className="size-4" /></Button></> : <><div className="flex gap-5"><BookCover book={selected} className="h-36 w-24 shrink-0 rounded-r shadow-md" /><div><h3 className="font-serif text-2xl">{selected.judul}</h3><p className="mt-2 text-xs text-stone-500">{selected.penulis}</p><p className="mt-3 text-xs leading-6 text-stone-600">{selected.deskripsi}</p></div></div><div className="my-6 flex items-start gap-3 rounded-md border border-stone-200 bg-white p-4"><BookOpen className="mt-0.5 size-4 shrink-0 text-stone-500" /><div><p className="text-xs font-medium">{data.mode === 'demo' ? 'Durasi peminjaman demo: 7 hari' : 'Peminjaman dikonfirmasi oleh petugas'}</p><p className="mt-2 text-[11px] leading-5 text-stone-500">{data.mode === 'demo' ? `Estimasi batas pengembalian ${dateLabel(relativeDay(7))}.` : 'Batas pengembalian dan denda mengikuti kebijakan perpustakaan yang ditetapkan server.'}</p></div></div>{error && <p role="alert" className="mb-4 text-xs text-red-700">{error}</p>}<Button className="w-full" disabled={busy || selected.stok < 1 || hasLoan(selected)} onClick={borrow}>{busy ? 'Mengajukan…' : hasLoan(selected) ? 'Sudah dalam peminjaman Anda' : selected.stok < 1 ? 'Buku sedang tidak tersedia' : 'Ajukan peminjaman'}<ArrowRight className="size-4" /></Button></>}
    </Modal>}
  </>;
}
