import { ArrowDownLeft, ArrowRight, ArrowUpRight, BookOpen, Check, Clock3, LibraryBig, Users, Wallet } from 'lucide-react';
import { useState } from 'react';
import { Badge, BookCover, Button } from './ui';
import { dateLabel, dayKey, isOpenLoan, loanStatus, number, rupiah, userId } from './data';
import { LoanTable } from './transactions';

export function AttendanceWidget({ data, user, onAttendance }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const entry = data.attendance.find((item) => String(item.id_user) === String(userId(user)) && item.tanggal?.slice(0, 10) === dayKey());
  const shift = data.shifts.find((item) => String(item.id_shift) === String(entry?.id_shift ?? user.id_shift));
  const late = entry?.jam_masuk_aktual && shift && entry.jam_masuk_aktual.slice(0, 5) > shift.jam_masuk.slice(0, 5);
  async function submit() {
    setBusy(true); setError('');
    try { await onAttendance(entry?.jam_masuk_aktual ? 'keluar' : 'masuk'); } catch (error) { setError(error.message); } finally { setBusy(false); }
  }
  return <section aria-label="Absensi hari ini" className="mb-6 rounded-lg border border-stone-200 bg-white px-5 py-4"><div className="flex flex-wrap items-center gap-x-6 gap-y-4"><div className="flex min-w-0 flex-1 items-center gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-md bg-[#f0f1eb] text-[#637052]"><Clock3 className="size-5" strokeWidth={1.4} /></span><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xs font-medium">Absensi hari ini</h2><Badge tone={entry?.jam_masuk_aktual ? late ? 'danger' : 'success' : 'neutral'}>{entry?.jam_masuk_aktual ? late ? 'Terlambat' : 'Tepat Waktu' : 'Belum absen'}</Badge></div><p className="mt-1.5 text-[10px] text-stone-500">{shift ? `${shift.nama_shift} · ${shift.jam_masuk.slice(0, 5)} – ${shift.jam_keluar.slice(0, 5)} WIB` : 'Jadwal shift belum ditetapkan'}</p></div></div><div className="flex gap-6"><div><p className="text-[9px] uppercase tracking-wider text-stone-400">Jam masuk</p><p className="mt-1 font-serif text-lg tabular-nums">{entry?.jam_masuk_aktual?.slice(0, 5) || '—'}<span className="ml-1.5 font-sans text-[9px] text-stone-400">WIB</span></p></div><div><p className="text-[9px] uppercase tracking-wider text-stone-400">Jam keluar</p><p className="mt-1 font-serif text-lg tabular-nums">{entry?.jam_keluar_aktual?.slice(0, 5) || '—'}<span className="ml-1.5 font-sans text-[9px] text-stone-400">WIB</span></p></div></div><Button secondary disabled={busy || !shift || Boolean(entry?.jam_keluar_aktual)} onClick={submit}>{entry?.jam_keluar_aktual ? <Check className="size-3.5" /> : <ArrowUpRight className="size-3.5" />}{busy ? 'Menyimpan…' : entry?.jam_keluar_aktual ? 'Shift selesai' : entry?.jam_masuk_aktual ? 'Absen Keluar' : 'Absen Masuk'}</Button></div>{error && <p role="alert" className="mt-3 text-xs text-red-700">{error}</p>}</section>;
}

export default function Overview({ data, onNavigate }) {
  const activeLoans = data.loans.filter(isOpenLoan);
  const lateLoans = activeLoans.filter((loan) => loanStatus(loan) === 'Terlambat');
  const stats = [
    { title: 'Total Buku', value: number(data.books.length), unit: 'judul', note: `${number(data.books.reduce((sum, book) => sum + Number(book.stok || 0), 0))} eksemplar tersedia`, icon: LibraryBig },
    { title: 'Peminjaman Aktif', value: number(activeLoans.length), unit: 'transaksi', note: `${lateLoans.length} melewati batas pengembalian`, icon: BookOpen, warning: lateLoans.length > 0 },
    { title: 'Denda Terkumpul', value: rupiah(data.loans.filter((loan) => loan.status === 'Dikembalikan').reduce((sum, loan) => sum + Number(loan.denda || 0), 0)), note: 'Dari transaksi yang dikembalikan', icon: Wallet },
    { title: 'Anggota Aktif', value: number(data.users.filter((user) => Number(user.id_role) === 3 && user.aktif !== false).length), unit: 'anggota', note: 'Terdaftar di perpustakaan', icon: Users },
  ];
  return <div className="space-y-6">
    <section aria-label="Statistik perpustakaan" className="grid grid-cols-2 gap-3 xl:grid-cols-4">{stats.map(({ title, value, unit, note, icon: Icon, warning }) => <article key={title} className="rounded-lg border border-stone-200 bg-white p-4 xl:p-5"><div className="flex items-center justify-between gap-2"><h2 className="text-[11px] text-stone-500">{title}</h2><Icon aria-hidden="true" className="size-4 shrink-0 text-stone-400" strokeWidth={1.4} /></div><p className="mb-4 mt-4 font-serif text-[30px] leading-none tracking-tight tabular-nums">{value}<span className="ml-2 font-sans text-[9px] tracking-normal text-stone-400">{unit}</span></p><p className={`flex items-center gap-1.5 border-t border-stone-100 pt-3 text-[9px] ${warning ? 'text-[#a17342]' : 'text-stone-500'}`}><span className={`size-1 shrink-0 rounded-full ${warning ? 'bg-[#b18b5d]' : 'bg-stone-300'}`} />{note}</p></article>)}</section>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_260px]">
      <section className="min-w-0 overflow-hidden rounded-lg border border-stone-200 bg-white"><div className="flex items-start justify-between gap-3 p-5"><div><h2 className="font-serif text-xl">Peminjaman terbaru</h2><p className="mt-1.5 text-[10px] text-stone-500">Cerita yang sedang dalam perjalanan.</p></div><button onClick={() => onNavigate('peminjaman')} className="mt-1 flex shrink-0 items-center gap-1.5 text-[10px] text-stone-600">Lihat semua <ArrowUpRight className="size-3.5" /></button></div><LoanTable data={data} loans={data.loans.slice(0, 4)} compact /></section>
      <section className="rounded-lg border border-stone-200 bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-serif text-xl">Perlu perhatian</h2><span className="flex size-5 items-center justify-center rounded-full bg-stone-100 text-[9px]">{lateLoans.length + data.loans.filter((loan) => loan.status === 'Menunggu').length}</span></div><p className="mb-5 mt-1.5 text-[10px] text-stone-500">Hal kecil, pelayanan lebih baik.</p><div className="space-y-5">{[{ icon: Clock3, title: 'Pengembalian terlambat', count: lateLoans.length, text: 'peminjaman melewati tenggat', page: 'peminjaman' }, { icon: ArrowDownLeft, title: 'Menunggu konfirmasi', count: data.loans.filter((loan) => loan.status === 'Menunggu').length, text: 'pengajuan perlu ditinjau', page: 'peminjaman' }, { icon: LibraryBig, title: 'Stok buku habis', count: data.books.filter((book) => book.stok < 1).length, text: 'judul perlu ditambahkan', page: 'buku' }].map(({ icon: Icon, title, count, text, page }) => <button key={title} onClick={() => onNavigate(page)} className="flex w-full items-start gap-3 text-left"><span className="flex size-8 shrink-0 items-center justify-center rounded bg-[#f5f2ec]"><Icon className="size-3.5 text-stone-500" strokeWidth={1.5} /></span><span className="flex-1"><span className="block text-[10px] font-medium">{title}</span><span className="mt-1.5 block text-[9px] leading-4 text-stone-500">{count} {text}</span></span><ArrowRight className="mt-2 size-3 text-stone-400" /></button>)}</div></section>
    </div>
    <section className="rounded-lg border border-stone-200 bg-white p-5"><div className="mb-5 flex items-start justify-between"><div><h2 className="font-serif text-xl">Dari rak perpustakaan</h2><p className="mt-1.5 text-[10px] text-stone-500">Pilihan cerita untuk setiap rasa ingin tahu.</p></div><button onClick={() => onNavigate('buku')} className="mt-1 flex items-center gap-1.5 text-[10px] text-stone-600">Jelajahi koleksi <ArrowUpRight className="size-3.5" /></button></div><div className="grid grid-cols-2 gap-5 xl:grid-cols-4">{data.books.slice(0, 4).map((book) => <button onClick={() => onNavigate('buku')} key={book.id_buku} className="group flex items-center gap-3 text-left"><BookCover book={book} className="h-[84px] w-14 shrink-0 rounded-r shadow-sm transition-transform group-hover:-translate-y-1 motion-reduce:transform-none" /><div className="min-w-0"><p className="line-clamp-2 font-serif text-[15px] leading-5">{book.judul}</p><p className="mt-1.5 truncate text-[9px] text-stone-500">{book.penulis}</p><p className="mt-2.5 text-[9px] text-[#687253]">{book.stok} tersedia</p></div></button>)}</div></section>
    <p className="sr-only">Data per {dateLabel(dayKey())}</p>
  </div>;
}
