import { useState } from 'react';
import { CalendarClock, Pencil, Plus, Users } from 'lucide-react';
import { Badge, BookCover, Button, EmptyState, Modal, SearchInput } from './ui';
import { dateLabel, dayKey, roleNames } from './data';

export function ResourceEditor({ resource, record, data, onSave, onClose }) {
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const titles = { books: 'buku', facilities: 'fasilitas', users: 'karyawan', shifts: 'shift' };
  const field = (name, label, options = {}) => <label className={`block ${options.wide ? 'col-span-full' : ''}`}><span className="mb-2 block text-[11px] font-medium">{label}</span>{options.textarea ? <textarea className="dash-input min-h-24 resize-y" name={name} defaultValue={record?.[name] || ''} maxLength={2000} /> : options.choices ? <select className="dash-input" name={name} defaultValue={record?.[name] ?? options.choices[0]?.value} required>{options.choices.map((choice) => <option value={choice.value} key={choice.value}>{choice.label}</option>)}</select> : <input className="dash-input" name={name} type={options.type || 'text'} min={options.type === 'number' ? 0 : undefined} max={options.type === 'number' ? 1000000 : undefined} step={options.type === 'number' ? 1 : undefined} required={!options.optional} maxLength={options.type === 'password' ? 128 : 250} minLength={options.type === 'password' ? 8 : undefined} autoComplete={options.type === 'password' ? 'new-password' : undefined} defaultValue={record?.[name] ?? options.defaultValue ?? ''} placeholder={options.placeholder} />}</label>;
  async function submit(event) {
    event.preventDefault();
    if (busy) return;
    const values = Object.fromEntries(new FormData(event.currentTarget));
    for (const key of Object.keys(values)) {
      if (key !== 'password') values[key] = values[key].trim();
      if (['stok', 'jumlah', 'id_role', 'id_shift', 'id_genre', 'id_penerbit', 'id_status'].includes(key)) values[key] = Number(values[key]);
    }
    if (Object.entries(values).some(([key, value]) => typeof value === 'string' && !value && !['deskripsi', 'gambar'].includes(key))) { setError('Lengkapi semua kolom wajib.'); return; }
    if (resource === 'shifts' && values.jam_keluar <= values.jam_masuk) { setError('Jam keluar harus setelah jam masuk untuk shift harian.'); return; }
    setError(''); setBusy(true);
    try { await onSave(resource, values, record); onClose(); } catch (error) { setError(error.message); } finally { setBusy(false); }
  }
  return <Modal title={`${record ? 'Edit' : 'Tambah'} ${titles[resource]}`} description="Kelola dengan rapi, layani dengan sepenuh hati." onClose={onClose} busy={busy}><form onSubmit={submit} onKeyDown={(event) => { if (event.key === 'Enter' && (event.nativeEvent.isComposing || event.keyCode === 229)) event.preventDefault(); }}><fieldset disabled={busy} className="grid grid-cols-2 gap-4">
    {resource === 'books' && <>{field('judul', 'Judul buku', { wide: true })}{field('penulis', 'Penulis', { wide: true })}{field('id_genre', 'Genre', { choices: data.genres.map((item) => ({ value: item.id_genre, label: item.nama_genre })) })}{field('id_penerbit', 'Penerbit', { choices: data.publishers.map((item) => ({ value: item.id_penerbit, label: item.nama_penerbit })) })}{field('stok', 'Stok tersedia', { type: 'number', defaultValue: 1 })}{field('id_status', 'Status', { choices: data.statuses.map((item) => ({ value: item.id_status, label: item.nama_status })) })}{field('gambar', 'URL gambar sampul (opsional)', { wide: true, optional: true, type: 'url', placeholder: 'https://…' })}{field('deskripsi', 'Deskripsi', { wide: true, textarea: true })}</>}
    {resource === 'facilities' && <>{field('nama_fasilitas', 'Nama fasilitas', { wide: true })}{field('jumlah', 'Jumlah', { type: 'number', defaultValue: 1 })}{field('kondisi', 'Kondisi', { choices: ['Baik', 'Perlu perbaikan', 'Rusak'].map((value) => ({ value, label: value })) })}</>}
    {resource === 'users' && <>{field('nama', 'Nama lengkap', { wide: true })}{field('username', 'Username', { wide: true })}{field('id_role', 'Peran', { choices: [{ value: 2, label: 'Pustakawan' }, { value: 1, label: 'Administrator' }] })}{field('id_shift', 'Jadwal shift', { choices: data.shifts.map((shift) => ({ value: shift.id_shift, label: shift.nama_shift })) })}{!record && field('password', 'Password awal', { type: 'password', wide: true })}</>}
    {resource === 'shifts' && <>{field('nama_shift', 'Nama shift', { wide: true })}{field('jam_masuk', 'Jam masuk', { type: 'time', defaultValue: '08:00' })}{field('jam_keluar', 'Jam keluar', { type: 'time', defaultValue: '16:00' })}</>}
  </fieldset>{error && <p role="alert" className="mt-4 text-xs text-red-700">{error}</p>}<div className="mt-7 flex justify-end gap-3"><Button type="button" secondary disabled={busy} onClick={onClose}>Batal</Button><Button type="submit" disabled={busy}>{busy ? 'Menyimpan…' : 'Simpan perubahan'}</Button></div></form></Modal>;
}

export function BookManagement({ data, onEdit }) {
  const [search, setSearch] = useState('');
  const [genre, setGenre] = useState('');
  const books = data.books.filter((book) => `${book.judul} ${book.penulis}`.toLowerCase().includes(search.toLowerCase()) && (!genre || String(book.id_genre) === genre));
  return <section className="overflow-hidden rounded-lg border border-stone-200 bg-white"><div className="flex flex-wrap gap-3 border-b border-stone-200 p-5"><SearchInput value={search} onChange={setSearch} /><select className="dash-input w-auto" aria-label="Filter genre" value={genre} onChange={(event) => setGenre(event.target.value)}><option value="">Semua genre</option>{data.genres.map((item) => <option key={item.id_genre} value={item.id_genre}>{item.nama_genre}</option>)}</select></div>{books.length ? <div className="overflow-x-auto"><table className="dash-table"><thead><tr><th>Buku & penulis</th><th>Genre</th><th>Penerbit</th><th>Stok</th><th><span className="sr-only">Tindakan</span></th></tr></thead><tbody>{books.map((book) => <tr key={book.id_buku}><td><div className="flex min-w-48 items-center gap-3"><BookCover book={book} className="h-14 w-9 shrink-0 rounded-r-sm" /><div><p className="font-serif text-base">{book.judul}</p><p className="mt-1 text-[10px] text-stone-500">{book.penulis}</p></div></div></td><td>{data.genres.find((item) => String(item.id_genre) === String(book.id_genre))?.nama_genre || '—'}</td><td>{data.publishers.find((item) => String(item.id_penerbit) === String(book.id_penerbit))?.nama_penerbit || '—'}</td><td><Badge tone={book.stok > 0 ? 'success' : 'danger'}>{book.stok > 0 ? `${book.stok} tersedia` : 'Stok habis'}</Badge></td><td><button aria-label={`Edit ${book.judul}`} onClick={() => onEdit('books', book)} className="rounded p-2 text-stone-500 hover:bg-stone-100"><Pencil className="size-3.5" /></button></td></tr>)}</tbody></table></div> : <EmptyState title="Buku tidak ditemukan" description="Coba judul, penulis, atau genre yang berbeda." />}<p className="border-t border-stone-100 px-5 py-4 text-[10px] text-stone-400">{books.length} judul dalam koleksi</p></section>;
}

export function Facilities({ data, onEdit }) {
  return <section className="overflow-hidden rounded-lg border border-stone-200 bg-white"><div className="border-b border-stone-200 p-5"><h2 className="font-serif text-xl">Ruang yang terawat</h2><p className="mt-2 text-xs text-stone-500">Inventaris untuk kenyamanan setiap pembaca.</p></div>{!data.facilities.length ? <EmptyState /> : <div className="overflow-x-auto"><table className="dash-table"><thead><tr><th>Nama fasilitas</th><th>Jumlah</th><th>Kondisi</th><th><span className="sr-only">Tindakan</span></th></tr></thead><tbody>{data.facilities.map((item) => <tr key={item.id_fasilitas}><td className="font-medium text-stone-800">{item.nama_fasilitas}</td><td>{item.jumlah} unit</td><td><Badge tone={item.kondisi === 'Baik' ? 'success' : 'warning'}>{item.kondisi}</Badge></td><td><button aria-label={`Edit ${item.nama_fasilitas}`} onClick={() => onEdit('facilities', item)} className="rounded p-2 hover:bg-stone-100"><Pencil className="size-3.5" /></button></td></tr>)}</tbody></table></div>}</section>;
}

export function Employees({ data, onEdit }) {
  return <div className="space-y-6"><section className="overflow-hidden rounded-lg border border-stone-200 bg-white"><div className="flex items-center gap-2 border-b border-stone-200 p-5"><Users className="size-4 text-stone-500" /><h2 className="font-serif text-xl">Di balik setiap pelayanan</h2></div><div className="overflow-x-auto"><table className="dash-table"><thead><tr><th>Karyawan</th><th>Peran</th><th>Shift</th><th><span className="sr-only">Tindakan</span></th></tr></thead><tbody>{data.users.filter((user) => [1, 2].includes(Number(user.id_role))).map((user) => <tr key={user.id_user}><td><p className="font-medium text-stone-800">{user.nama || user.username}</p><p className="mt-1 text-[10px] text-stone-400">@{user.username}</p></td><td>{roleNames[user.id_role]}</td><td>{data.shifts.find((shift) => String(shift.id_shift) === String(user.id_shift))?.nama_shift || 'Belum ditetapkan'}</td><td><button aria-label={`Edit ${user.nama || user.username}`} onClick={() => onEdit('users', user)} className="rounded p-2 hover:bg-stone-100"><Pencil className="size-3.5" /></button></td></tr>)}</tbody></table></div></section><section><div className="mb-4 flex items-center justify-between"><h2 className="font-serif text-xl">Jadwal shift</h2><Button secondary onClick={() => onEdit('shifts')}><Plus className="size-3.5" />Tambah shift</Button></div><div className="grid gap-4 sm:grid-cols-2">{data.shifts.map((shift) => <article key={shift.id_shift} className="flex items-center gap-4 rounded-lg border border-stone-200 bg-white p-5"><CalendarClock className="size-6 text-stone-400" strokeWidth={1.3} /><div className="flex-1"><h3 className="font-serif text-lg">{shift.nama_shift}</h3><p className="mt-2 text-xs text-stone-500">{shift.jam_masuk.slice(0, 5)} – {shift.jam_keluar.slice(0, 5)} WIB</p></div><button aria-label={`Edit ${shift.nama_shift}`} onClick={() => onEdit('shifts', shift)} className="rounded p-2 hover:bg-stone-100"><Pencil className="size-3.5" /></button></article>)}</div></section></div>;
}

export function AttendanceReport({ data }) {
  const [date, setDate] = useState(dayKey());
  const attendance = data.attendance.filter((entry) => !date || entry.tanggal?.slice(0, 10) === date);
  return <section className="overflow-hidden rounded-lg border border-stone-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-stone-200 p-5"><div><h2 className="font-serif text-xl">Catatan kehadiran</h2><p className="mt-2 text-[10px] text-stone-500">{attendance.length} catatan {date ? `pada ${dateLabel(date)}` : 'keseluruhan'}</p></div><label className="flex items-center gap-3 text-[10px] text-stone-500">Tanggal<input className="dash-input w-auto" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label></div>{!attendance.length ? <EmptyState title="Belum ada absensi" description="Pilih tanggal lain untuk melihat catatan kehadiran staf." /> : <div className="overflow-x-auto"><table className="dash-table"><thead><tr><th>Karyawan</th><th>Jadwal masuk</th><th>Masuk aktual</th><th>Keluar aktual</th><th>Status</th></tr></thead><tbody>{attendance.map((entry) => {
    const user = data.users.find((user) => String(user.id_user) === String(entry.id_user));
    const shift = data.shifts.find((shift) => String(shift.id_shift) === String(entry.id_shift));
    const late = shift && entry.jam_masuk_aktual?.slice(0, 5) > shift.jam_masuk.slice(0, 5);
    return <tr key={entry.id_absensi}><td><p className="font-medium">{user?.nama || user?.username || 'Staf'}</p><p className="mt-1 text-[9px] text-stone-400">{dateLabel(entry.tanggal)}</p></td><td>{shift?.jam_masuk.slice(0, 5) || '—'}</td><td>{entry.jam_masuk_aktual?.slice(0, 5) || '—'}</td><td>{entry.jam_keluar_aktual?.slice(0, 5) || '—'}</td><td><Badge tone={!shift || !entry.jam_masuk_aktual ? 'neutral' : late ? 'danger' : 'success'}>{!shift || !entry.jam_masuk_aktual ? 'Belum diketahui' : late ? 'Terlambat' : 'Tepat Waktu'}</Badge></td></tr>;
  })}</tbody></table></div>}</section>;
}
